<?php

if (!isset($cols) || !isset($rows))
{
    exit("Minesweeper.php: missing parameter(s)");
}

?>

<!-- The following HTML is generated by a script.  See ./source.php -->

<div style=" margin: 0 auto; text-align: center;"><button id ="returnMenuButton" style="font-size: 20px; background-color: #cccccc; color: black; font-family: times; font-style: bold;">
<strong> Change Game Mode </strong></button></div>

<TABLE ID=sqTable onmouseup="return false">
    <TR>
        <TD CLASS=score COLSPAN=<?php echo $cols?>>
            <IMG ID=smiley SRC="../img/erasing.gif" ALT=""
            onmousedown="return clickSmiley(event)">
        <P ID = "loadingId">Loading...</P>
        </TD>
    </TR>

    <?php
    for ($row = 0; $row < $rows; $row++)
    {
    ?>
        <TR>
            <?php
            for ($col = 0; $col < $cols; $col++)
	    {
            ?>
            <TD CLASS=sq ID="sq-<?php echo $row * $cols + $col?>"
                 onmousedown="return clickSq(event,<?php echo $row * $cols + $col ?>)"
                 >&nbsp;
            </TD>
            <?php
            }
            ?>
        </TR>
    <?php
    }
    ?>
</TABLE>
<!-- End of script-generated HTML -->
<script>

var buttonClick = document.getElementById('returnMenuButton');

function buttonFunction()
{
	switch(gameMode)
	{
		case 0:
         		window.location.href = "/";
		break;

		case 1:
         		window.location.href = "/minesweeper/index_p1_vs_p2_turn.php";
		break;

		case 2:
         		window.location.href = "/minesweeper/index_turn.php";
		break;

		case 3:
         		window.location.href = "/minesweeper/index_p3_vs_p4_turn.php";
		break;

		case 4:
         		window.location.href = "/minesweeper/index_turn.php";
		break;
	}
}
buttonClick.addEventListener('click',buttonFunction,false);
</script>
